apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-java
  labels:
    app: k8s-java
spec:
  replicas: 3
  selector:
    matchLabels:
      app: k8s-java
  template:
    metadata:
      labels:
        app: k8s-java
    spec:
      containers:
      - name: k8s-java
        image: k8s-java
        env:
        - name: name
          value: "Carl Benz"
        - name: license
          value: "53cr3t"
        ports:
        - containerPort: 8080