apiVersion: v1
kind: Service
metadata:
  labels:
    app: k8s-java
  name: k8s-java
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-java
  type: LoadBalancer